global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'pubsub'

receivers:
  - name: 'pubsub'
    webhook_configs:
      - url: 'http://${WEB_IP}:9095/alerts'