groups:
- name: django_alerts
  rules:
  - alert: FailedLoginAttempt
    expr: increase(django_failed_login_total[1m]) >= 1
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: Failed Login Attempt
      description: "Failed login attempt detected"

  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High CPU Usage
      description: "CPU usage is above 80%"