name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  ZONE: us-central1-a

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Auth to GCP
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Extract Service Account Email
      id: sa-email
      run: |
        SA_EMAIL=$(echo '${{ secrets.GCP_SA_KEY }}' | jq -r '.client_email')
        echo "SA_EMAIL=$SA_EMAIL" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Create terraform.tfvars
      run: |
        cat > terraform/terraform.tfvars << EOF
        project_id = "${{ secrets.GCP_PROJECT_ID }}"
        region = "${{ env.REGION }}"
        zone = "${{ env.ZONE }}"
        db_password = "${{ secrets.DB_PASSWORD }}"
        notification_email = "${{ secrets.NOTIFICATION_EMAIL }}"
        notification_email_password = "${{ secrets.EMAIL_APP_PASSWORD }}"
        alert_email_recipients = ${{ secrets.ALERT_EMAILS }}
        service_account_email = "${{ env.SA_EMAIL }}"
        EOF

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Validate
      working-directory: ./terraform
      run: terraform validate

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      working-directory: ./terraform
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: ./terraform
      run: terraform apply -auto-approve

    - name: Setup Database
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # Get DB server IP
        DB_IP=$(terraform -chdir=terraform output -raw db_server_public_ip)
        
        # Configure PostgreSQL
        gcloud compute ssh db-server --zone=${{ env.ZONE }} --command "
          # Create database and user
          sudo -u postgres psql -c \"CREATE USER django_user WITH PASSWORD '${{ secrets.DB_PASSWORD }}';\" || true
          sudo -u postgres psql -c \"CREATE DATABASE django_db OWNER django_user;\" || true
          
          # Configure PostgreSQL networking
          sudo sh -c 'echo \"host    django_db    django_user    10.0.0.0/24    md5\" >> /etc/postgresql/12/main/pg_hba.conf'
          sudo sed -i \"s/#listen_addresses = 'localhost'/listen_addresses = '*'/\" /etc/postgresql/12/main/postgresql.conf
          
          # Restart PostgreSQL
          sudo systemctl restart postgresql"

    - name: Deploy Django App
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # Get outputs
        WEB_IP=$(terraform -chdir=terraform output -raw web_server_public_ip)
        DB_IP=$(terraform -chdir=terraform output -raw db_server_private_ip)
        
        # Create Django environment file
        cat > .env << EOF
        DEBUG=False
        DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
        DB_NAME=django_db
        DB_USER=django_user
        DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        DB_HOST=$DB_IP
        DB_PORT=5432
        ALLOWED_HOSTS=$WEB_IP,localhost,127.0.0.1
        GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }}
        EOF

        # Create deployment directory
        DEPLOY_DIR="deploy_package"
        mkdir -p $DEPLOY_DIR
        cp -r manage.py requirements.txt todoApp todos staticfiles $DEPLOY_DIR/
        cp .env $DEPLOY_DIR/
        mkdir -p $DEPLOY_DIR/staticfiles

        # Setup on web server
        gcloud compute ssh web-server --zone=${{ env.ZONE }} --command "
          # Setup directories and permissions
          sudo mkdir -p /opt/django-app /opt/django-app/logs
          sudo chown -R \$USER:\$USER /opt/django-app
          
          # Install Gunicorn
          python3 -m pip install gunicorn

          # Create systemd service file for Gunicorn
          sudo tee /etc/systemd/system/gunicorn.service << 'EOL'
          [Unit]
          Description=Gunicorn daemon for Django application
          After=network.target

          [Service]
          User=$USER
          Group=$USER
          WorkingDirectory=/opt/django-app
          ExecStart=/opt/django-app/venv/bin/gunicorn --workers 3 --bind 0.0.0.0:8000 todoApp.wsgi:application --access-logfile /opt/django-app/logs/access.log --error-logfile /opt/django-app/logs/error.log
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOL"

        # Copy files to web server
        gcloud compute scp --recurse $DEPLOY_DIR/* web-server:/opt/django-app/ --zone=${{ env.ZONE }}
        gcloud compute scp $DEPLOY_DIR/.env web-server:/opt/django-app/ --zone=${{ env.ZONE }}

        # Setup and start Django with Gunicorn
        gcloud compute ssh web-server --zone=${{ env.ZONE }} --command "
          cd /opt/django-app && \
          python3 -m venv venv && \
          source venv/bin/activate && \
          pip install -r requirements.txt gunicorn && \
          python3 manage.py migrate && \
          python3 manage.py collectstatic --noinput && \
          sudo systemctl daemon-reload && \
          sudo systemctl enable gunicorn && \
          sudo systemctl restart gunicorn"

    - name: Run Lynis Security Scan
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # Run Lynis on web server
        gcloud compute ssh web-server --zone=${{ env.ZONE }} --command "
          sudo lynis audit system --quick --no-colors > /opt/django-app/logs/lynis-web.log 2>&1"

        # Run Lynis on db server
        gcloud compute ssh db-server --zone=${{ env.ZONE }} --command "
          sudo lynis audit system --quick --no-colors > /var/log/lynis-db.log 2>&1"

        echo "Security scans completed and logged"